# Generated by Django 5.2.12 on 2026-07-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField()),
                ('source_name', models.CharField(default='Typed_Dump', max_length=255)),
                ('source_type', models.CharField(choices=[('text', 'Text'), ('txt_file', 'Text File'), ('docx', 'Word Document'), ('image', 'Image'), ('pdf', 'PDF')], default='text', max_length=10)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('campus', models.CharField(default='LASU', max_length=50)),
                ('course_code', models.CharField(blank=True, max_length=50, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('extracted_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dump',
                'verbose_name_plural': 'Dumps',
                'ordering': ['-created_at'],
            },
        ),
    ]
