# Generated by Django 6.0.7 on 2026-07-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default='default', max_length=100)),
                ('user_query', models.TextField()),
                ('assistant_response', models.TextField(blank=True, default='')),
                ('mode', models.CharField(default='fast', max_length=20)),
                ('status', models.CharField(default='grounded', max_length=20)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('latency', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
